development:
  sessions:
    default:
      database: wherearetheyat_development
      hosts:
        - localhost:27017
      options:

  options:

test:
  sessions:
    default:
      database: wherearetheyat_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0

production:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
      options:
        consistency: :strong